### ISSUE TITLE
Preprocessing data

### ISSUE THREAD

**Issue by billquan** [typilus/typilus#12]
Hi!
I'm trying to reproduce the dataset and the results.
I followed the instructions and ran the bash file just like [urialon](https://github.com/urialon) did in this issue post https://github.com/typilus/typilus/issues/1.
However, I found that the script seemed to take a long time and take a lot up memory. The single process of pytype ate up 79% of the 49 GB memory in 11 hrs. I wonder is this a normal behavior? Or do we have to discard pytype now? How did you manage to preprocess the dataset initially?
Thanks!

**Comment by mallamanis** [comment]
Hi @billquan ,

Thanks for your interest. Indeed, it seems that pytype is now taking too long. I suspect that a change pytype has caused this issue. Despite this, I don't think that there's an easy way to replicate the original extraction (I don't have the original environment). So, I'd suggest removing the pytype step.

Alternatively, @mir-am has the [ManyTypes4Py](https://zenodo.org/record/5244636) dataset which might also be of help here.

**Comment by billquan** [comment]
Thank you! Appreciate the quick reply. I'll try run without pytype.

**Comment by billquan** [comment]
Hi @mallamanis,
Just wonder if by any chance you have the pretrained model? I guess that could possibly be easier for others too, if they want to try out the model.

**Comment by mallamanis** [comment]
Yes, one the pretrained model can found here:
https://github.com/typilus/typilus-action/releases/download/v0.1/typilus20200507.pkl.gz

**Comment by billquan** [comment]
I tried to use this model with: https://github.com/typilus/typilus/tree/master/src#test-the-model
But it gave me the following error:
```
Traceback (most recent call last):
  File "typilus/utils/predict.py", line 77, in <module>
    run_and_debug(lambda: run(args), args.get('--debug', False))
  File "***/.local/lib/python3.6/site-packages/dpu_utils/utils/debughelper.py", line 21, in run_and_debug
    func()
  File "typilus/utils/predict.py", line 77, in <lambda>
    run_and_debug(lambda: run(args), args.get('--debug', False))
  File "typilus/utils/predict.py", line 73, in run
    run_predict(model_path, test_folder, output_file)
  File "typilus/utils/predict.py", line 43, in run_predict
    model = model_restore_helper.restore(model_path, is_train=False, hyper_overrides=test_hyper_overrides)
  File "***/typilus/src/typilus/model/model_restore_helper.py", line 46, in restore
    saved_data['hyperparameters'].update(hyper_overrides)
TypeError: 'int' object is not subscriptable
```
Did I miss something?

**Comment by billquan** [comment]
Hi @mallamanis,

I trained a model without pytype and I'm trying to reproduce @[urialon](https://github.com/urialon)'s results.
I followed exactly the steps you guys mentioned in https://github.com/typilus/typilus/issues/2#issuecomment-678343451.
However, the weird thing is that I got a None Error as follows when running test.py:
```
Traceback (most recent call last):
  File "typilus/utils/test.py", line 224, in <module>
    run_and_debug(lambda: run(args), args.get('--debug', False))
  File "***/.local/lib/python3.6/site-packages/dpu_utils/utils/debughelper.py", line 21, in run_and_debug
    func()
  File "typilus/utils/test.py", line 224, in <lambda>
    run_and_debug(lambda: run(args), args.get('--debug', False))
  File "typilus/utils/test.py", line 219, in run
    arguments['--print-predictions'])
  File "typilus/utils/test.py", line 202, in run_test
    key=lambda x: annotation.predicted_annotation_logprob_dist[x])
ValueError: max() arg is an empty sequence
```
I tried to skip the error in the case that it's a rare and unexpected error by using "try - except" and continue the loop. However, in the end, the test.py gave me a Division By Zero Error:
```
Traceback (most recent call last):
  File "typilus/utils/test.py", line 227, in <module>
    run_and_debug(lambda: run(args), args.get('--debug', False))
  File "/home/haowei/.local/lib/python3.6/site-packages/dpu_utils/utils/debughelper.py", line 21, in run_and_debug
    func()
  File "typilus/utils/test.py", line 227, in <lambda>
    run_and_debug(lambda: run(args), args.get('--debug', False))
  File "typilus/utils/test.py", line 222, in run
    arguments['--print-predictions'])
  File "typilus/utils/test.py", line 212, in run_test
    print(json.dumps(evaluator.metrics(), indent=2, sort_keys=True))
  File "typilus/utils/test.py", line 138, in metrics
    'accuracy': self.__exact_match / self.__num_samples,
ZeroDivisionError: division by zero
```
Seems num_samples is zero. Any idea what I'm doing wrong?

**Comment by mallamanis** [comment]
The last set of errors suggest that no datapoints (data) was loaded. This propably means that you've pointed the `test.py` script to the wrong location or a location that doesn't have appropriately formatted files (e.g. suffix)

**Comment by billquan** [comment]
I can confirm that the location is correct and the test samples are there. The problem seems more likely in this error message:
```
File "typilus/utils/test.py", line 202, in run_test
    key=lambda x: annotation.predicted_annotation_logprob_dist[x])
ValueError: max() arg is an empty sequence
```
It seems that [predicted_annotation_logprob_dist](https://github.com/typilus/typilus/blob/69c377b4cd286fd3657708accf3b2f56a5da1e8d/src/typilus/utils/test.py#L201) is empty for every sample predication, so no data point was added [here](https://github.com/typilus/typilus/blob/69c377b4cd286fd3657708accf3b2f56a5da1e8d/src/typilus/utils/test.py#L206#207). 
I'm not sure what results in this... 
I pointed the `test.py` script to the `graph-dataset-split/test/` folder generated by `scripts/prepare_data.sh`. I assume those test dataset don't need to be tensorized (as I tried using tensorized test `.jsonl.gz` data and the output seemed more wrong).

**Comment by mallamanis** [comment]
Did you create the index first? https://github.com/typilus/typilus/blob/master/src/typilus/utils/index.py

**Comment by billquan** [comment]
Hi Miltos,
Sorry for the delay. I did create the index first. The following are the steps I followed.
1. data preparation using the docker image, without pytype (delete [L57-L72](https://github.com/typilus/typilus/blob/master/src/data_preparation/scripts/prepare_data.sh#L57#L72)). https://github.com/typilus/typilus/issues/1#issuecomment-653875912
2. `./tensorize_and_train.sh "graph2hybridmetric" data_preparation/container/graph-dataset-split/ tensorized_data`
3. `python3.6 typilus/utils/index.py tensorized_data/models/Graph2HybridMetric_graph2hybridmetric-2022-03-04-01-20-10_model_best.pkl.gz data_preparation/container/graph-dataset-split/train_and_val/`
4. `python3.6 typilus/utils/test.py tensorized_data/models/Graph2HybridMetric_graph2hybridmetric-2022-03-04-01-20-10_model_best.pkl.gz data_preparation/container/graph-dataset-split/test/ data_preparation/container/graph-dataset/_type_lattice.json.gz data_preparation/metadata/typingRules.json`

Is there any problem with these steps? Or is it possibly due to the environment (I'm using ubuntu 20.04)?

**Comment by mallamanis** [comment]
These steps seem reasonable. Have you verified how many points (i.e. `>0`) have been indexed?
